name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-engine:
    name: Build Engine
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements_engine.txt
          python -m pip install pywin32
          python -m pip install setuptools<70 --upgrade

      - name: Generate component files
        run: python -m app.engine.codegen.source_generator

      - name: Build with PyInstaller
        run: |
          cp ./utilities/build_tools/unemblem_engine.spec .
          python -m PyInstaller -y unemblem_engine.spec
          rm unemblem_engine.spec -fo

      - name: Package engine
        run: |
          mkdir unemblem
          mv dist/unemblem ./unemblem/unemblem
          cp utilities/install/double_click_to_play.bat ./unemblem
          cp app/engine/item_system.py ./unemblem/unemblem/app/engine
          cp app/engine/skill_system.py ./unemblem/unemblem/app/engine
          echo ${{ github.sha }} > ./unemblem/unemblem/version.txt

      - name: Zip engine
        run: powershell Compress-Archive -Path unemblem -DestinationPath UnEmblem.zip

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: UnEmblem.zip
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}